apiVersion: v1
kind: ConfigMap
metadata:
  name: meshdbconfig
  namespace: {{ .Values.meshdb_app_namespace }}
data:
  MESHDB_ENVIRONMENT: {{ .Values.meshweb.environment }}
  DB_NAME: {{ .Values.pg.dbname }}
  DB_USER: {{ .Values.pg.user | quote }}
  DB_HOST: {{ include "meshdb.fullname" . }}-postgres.{{ .Values.meshdb_app_namespace }}.svc.cluster.local
  DB_PORT: {{ .Values.pg.port | quote }}
  # Backups
  BACKUP_S3_BUCKET_NAME: {{ .Values.meshweb.backup_s3_bucket_name | quote }}
  BACKUP_S3_BASE_FOLDER: {{ .Values.meshweb.backup_s3_base_folder | quote }}

  SMTP_HOST: {{ .Values.email.smtp_host | quote }}
  SMTP_PORT: {{ .Values.email.smtp_port | quote }}
  SMTP_USER: {{ .Values.email.smtp_user | quote }}

  CELERY_BROKER: "redis://{{ include "meshdb.fullname" . }}-redis.{{ .Values.meshdb_app_namespace }}.svc.cluster.local:{{ .Values.redis.port }}/0"

  # Change to pelias:3000 when using full docker-compose
  PELIAS_ADDRESS_PARSER_URL: http://{{ include "meshdb.fullname" . }}-pelias.{{ .Values.meshdb_app_namespace }}.svc.cluster.local:{{ .Values.pelias.port }}/parser/parse

  # Comment this out to enter prod mode
  DEBUG: {{ .Values.meshweb.enable_debug | quote }}
  DISABLE_PROFILING: {{ .Values.meshweb.disable_profiling | quote }}

  # Comment this out to allow edits to the panoramas in the admin panel
  DISABLE_PANO_EDITS: {{ .Values.meshweb.disable_pano_edits | quote }}

  UISP_URL: {{ .Values.uisp.url | quote }}
  UISP_USER: {{ .Values.uisp.user | quote }}

  ADMIN_MAP_BASE_URL: {{ .Values.adminmap.base_url | quote }}
  MAP_BASE_URL: {{ .Values.map.base_url | quote }}
  LOS_URL: {{ .Values.meshweb.los_url | quote }}
  PG_ADMIN_URL: https://{{ .Values.global.pgadmin.fqdn }}
  FORMS_URL: {{ .Values.meshweb.forms_url | quote }}

  SITE_BASE_URL: {{ .Values.meshdb.site_base_url | quote }}
