apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Values.meshweb.static_pvc_name }}
  namespace: {{ .Values.meshdb_app_namespace }}
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: longhorn
  resources:
    requests:
      storage: {{ .Values.meshweb.static_pvc_size }}