apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "meshdb.fullname" . }}-pelias
  namespace: {{ .Values.meshdb_app_namespace }}
  labels:
    {{- include "meshdb.labels" . | nindent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "meshdb.selectorLabels" . | nindent 6 }}
  revisionHistoryLimit: {{ .Values.revisionHistoryLimit }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        app: meshdb-pelias-app
        admission.datadoghq.com/enabled: "false"
        {{- include "meshdb.labels" . | nindent 8 }}
        {{- with .Values.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      securityContext:
        {{- toYaml .Values.pelias.podSecurityContext | nindent 8 }}
      {{- if .Values.imageCredentials }}
      imagePullSecrets:
        - name: pull-secret
      {{- end }}
      containers:
        - name: {{ .Chart.Name }}-pelias
          securityContext:
            {{- toYaml .Values.pelias.securityContext | nindent 12 }}
          image: "docker.io/pelias/parser"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: pelias
              containerPort: {{ .Values.pelias.port }}
              protocol: TCP
          resources:
            {{- toYaml .Values.pelias.resources | nindent 12 }}
      {{- with .Values.pelias.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.pelias.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.pelias.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
