apiVersion: v1
kind: Service
metadata:
  name: {{ include "meshdb.fullname" . }}-postgres
  namespace: {{ .Values.meshdb_app_namespace }}
  labels:
    {{- include "meshdb.labels" . | nindent 4 }}
spec:
  type: NodePort
  ports:
    - port: 5432
      targetPort: 5432
      protocol: TCP
      name: postgres
      nodePort: 30432
  selector:
    app: meshdb-postgres-app