# Stolen basically verbatim from here
# https://forum.djangoproject.com/t/django-4-2-is-a-2nd-autofield-like-field-on-a-model-possible/28278
from typing import List, Tuple

from django.db.backends.base.base import BaseDatabaseWrapper
from django.db.models import Expression, IntegerField
from django.db.models.sql.compiler import SQLCompiler


class Default(Expression):
    def as_sql(self, compiler: SQLCompiler, connection: BaseDatabaseWrapper) -> Tuple[str, List[str | int]]:
        return "DEFAULT", []


class AutoIncrementingIntegerField(IntegerField):
    @property
    def db_returning(self) -> bool:
        return True

    def get_default(self) -> Expression:
        return Default()

    def db_type_suffix(self, connection: BaseDatabaseWrapper) -> str:
        return "GENERATED BY DEFAULT AS IDENTITY"
