# Stolen basically verbatim from here
# https://forum.djangoproject.com/t/django-4-2-is-a-2nd-autofield-like-field-on-a-model-possible/28278

from django.db.models import Expression, IntegerField


class Default(Expression):
    def as_sql(self, compiler, connection):
        return "DEFAULT", []


class AutoIncrementingIntegerField(IntegerField):
    @property
    def db_returning(self):
        return True

    def get_default(self):
        return Default()

    def db_type_suffix(self, connection):
        return "GENERATED BY DEFAULT AS IDENTITY"
