version: 2
updates:
- package-ecosystem: "pip"
  directory: "/"
  schedule:
    interval: "cron"
    cronjob: "41 8 * * *"
  assignees:
   - "james-otten"
- package-ecosystem: "docker"
  directory: "/"
  schedule:
    interval: "cron"
    cronjob: "4 8 * * *"
  assignees:
   - "james-otten"
- package-ecosystem: "github-actions"
  directory: "/"
  schedule:
    interval: "cron"
    cronjob: "44 8 * * *"
  assignees:
   - "james-otten"
