from typing import Literal

CountryLiteral = Literal[
    "Unknown",
    "Licensed",
    "Licensed (5170-6200 MHz)",
    "Canada Licensed",
    "Afghanistan",
    "Åland Islands",
    "Albania",
    "Algeria",
    "American Samoa",
    "Andorra",
    "Angola",
    "Anguilla",
    "Antarctica",
    "Antigua and Barbuda",
    "Argentina",
    "Armenia",
    "Aruba",
    "Australia",
    "Austria",
    "Azerbaijan",
    "Bahamas",
    "Bahrain",
    "Bangladesh",
    "Barbados",
    "Belarus",
    "Belgium",
    "Belize",
    "Benin",
    "Bermuda",
    "Bhutan",
    "Bolivia",
    "Bonaire, Sint Eustatius and Saba",
    "Bosnia and Herzegovina",
    "Botswana",
    "Bouvet Island",
    "Brazil",
    "British Indian Ocean Territory",
    "Brunei Darussalam",
    "Bulgaria",
    "Burkina Faso",
    "Burundi",
    "Cabo Verde",
    "Cambodia",
    "Cameroon",
    "Canada",
    "Cayman Islands",
    "Central Africa Republic",
    "Chad  ",
    "Chile",
    "China",
    "Christmas Island",
    "Cocos Islands",
    "Colombia",
    "Comoros",
    "Cook Islands",
    "Costa Rica",
    "Côte d'Ivoire",
    "Croatia",
    "Curaçao",
    "Cyprus",
    "Czech Republic",
    "Democratic Republic of the Congo",
    "Denmark",
    "Djibouti",
    "Dominica",
    "Dominican Republic",
    "Ecuador",
    "Egypt",
    "El Salvador",
    "Equatorial Guinea",
    "Eritrea",
    "Estonia",
    "Eswatini",
    "Ethiopia",
    "Falkland Islands",
    "Faroe Islands",
    "Fiji",
    "Finland",
    "France",
    "French Guiana",
    "French Polynesia",
    "French Southern Territories",
    "Gabon",
    "Gambia",
    "Georgia",
    "Germany",
    "Ghana",
    "Gibraltar",
    "Greece",
    "Greenland",
    "Grenada",
    "Guadeloupe",
    "Guam",
    "Guatemala",
    "Guernsey",
    "Guinea",
    "Guinea-Bissau",
    "Guyana",
    "Haiti",
    "Heard Island and McDonald Islands",
    "Honduras",
    "Hong Kong",
    "Hungary",
    "Iceland",
    "India",
    "Indonesia",
    "Iraq",
    "Ireland",
    "Isle of Man",
    "Israel",
    "Italy",
    "Jamaica",
    "Japan",
    "Jersey",
    "Jordan",
    "Kazakhstan",
    "Kenya",
    "Kiribati",
    "Kuwait",
    "Kyrgyzstan",
    "Lao People's Democratic Republic",
    "Latvia",
    "Lebanon",
    "Lesotho",
    "Liberia",
    "Libya",
    "Liechtenstein",
    "Lithuania",
    "Luxembourg",
    "Macau Sar",
    "Macedonia, Fyro",
    "Madagascar",
    "Malawi",
    "Malaysia",
    "Maldives",
    "Mali",
    "Malta",
    "Marshall Islands",
    "Martinique",
    "Mauritania",
    "Mauritius",
    "Mayotte",
    "Mexico",
    "Micronesia",
    "Moldova",
    "Monaco",
    "Mongolia",
    "Montenegro",
    "Montserrat",
    "Morocco",
    "Mozambique",
    "Myanmar",
    "Namibia",
    "Nauru",
    "Nepal",
    "Netherlands",
    "New Caledonia",
    "New Zealand",
    "Nicaragua",
    "Niger",
    "Nigeria",
    "Niue",
    "Norfolk Island",
    "Northern Mariana Islands",
    "Norway",
    "Oman",
    "Pakistan",
    "Palau",
    "Panama",
    "Papua New Guinea",
    "Paraguay",
    "Peru",
    "Philippines",
    "Pitcairn",
    "Poland",
    "Portugal",
    "Puerto Rico (U.S. territory)",
    "Qatar",
    "Republic of Korea",
    "Republic of Serbia",
    "Republic of Seychelles",
    "Republic of the Congo",
    "Reunion",
    "Romania",
    "Russia",
    "Rwanda",
    "Saint Barthélemy",
    "Saint Helena, Ascension and Tristan da Cunh",
    "Saint Kitts and Nevis",
    "Saint Lucia",
    "Saint Martin",
    "Saint Pierre Miquelon",
    "Saint Vincent Grenadiens",
    "Samoa",
    "San Marino",
    "Sao Tome and Principe",
    "Saudi Arabia",
    "Senegal",
    "Sierra Leone",
    "Singapore",
    "Sint Maarten",
    "Slovakia",
    "Slovenia",
    "Solomon Islands",
    "Somalia",
    "South Africa",
    "South Georgia and the South Sandwich Islands",
    "South Sudan",
    "Spain",
    "Sri Lanka",
    "State of Palestine",
    "Suriname",
    "Svalbard and Jan Mayen",
    "Sweden",
    "Switzerland",
    "Taiwan",
    "Tajikistan",
    "Tanzania",
    "Thailand",
    "Timor-Leste",
    "Togo",
    "Tokelau",
    "Tonga",
    "Trinidad and Tobago",
    "Tunisia",
    "Turkey",
    "Turkmenistan",
    "Turks Caicos",
    "Tuvalu",
    "Uganda",
    "Ukraine",
    "United Arab Emirates",
    "United Kingdom",
    "United States",
    "Uruguay",
    "Uzbekistan",
    "Vanuatu",
    "Vatican City State",
    "Venezuela",
    "Vietnam",
    "Virgin Islands (British)",
    "Virgin Islands (U.S.)",
    "Wallis Futuna",
    "Western Sahara",
    "Yemen",
    "Zambia",
    "Zimbabwe",
]

CountryCodeLiteral = Literal[
    "XX",
    "XY",
    "XL",
    "XH",
    "XC",
    "AF",
    "AX",
    "AL",
    "DZ",
    "AS",
    "AD",
    "AO",
    "AI",
    "AQ",
    "AG",
    "AR",
    "AM",
    "AW",
    "AU",
    "AT",
    "AZ",
    "BS",
    "BH",
    "BD",
    "BB",
    "BY",
    "BE",
    "BZ",
    "BJ",
    "BM",
    "BT",
    "BO",
    "BQ",
    "BA",
    "BW",
    "BV",
    "BR",
    "IO",
    "BN",
    "BG",
    "BF",
    "BI",
    "CV",
    "KH",
    "CM",
    "CA",
    "KY",
    "CF",
    "TD",
    "CL",
    "CN",
    "CX",
    "CC",
    "CO",
    "KM",
    "CK",
    "CR",
    "CI",
    "HR",
    "CW",
    "CY",
    "CZ",
    "CD",
    "DK",
    "DJ",
    "DM",
    "DO",
    "EC",
    "EG",
    "SV",
    "GQ",
    "ER",
    "EE",
    "SZ",
    "ET",
    "FK",
    "FO",
    "FJ",
    "FI",
    "FR",
    "GF",
    "PF",
    "TF",
    "GA",
    "GM",
    "GE",
    "DE",
    "GH",
    "GI",
    "GR",
    "GL",
    "GD",
    "GP",
    "GU",
    "GT",
    "GG",
    "GN",
    "GW",
    "GY",
    "HT",
    "HM",
    "HN",
    "HK",
    "HU",
    "IS",
    "IN",
    "ID",
    "IQ",
    "IE",
    "IM",
    "IL",
    "IT",
    "JM",
    "JP",
    "JE",
    "JO",
    "KZ",
    "KE",
    "KI",
    "KW",
    "KG",
    "LA",
    "LV",
    "LB",
    "LS",
    "LR",
    "LY",
    "LI",
    "LT",
    "LU",
    "MO",
    "MK",
    "MG",
    "MW",
    "MY",
    "MV",
    "ML",
    "MT",
    "MH",
    "MQ",
    "MR",
    "MU",
    "YT",
    "MX",
    "FM",
    "MD",
    "MC",
    "MN",
    "ME",
    "MS",
    "MA",
    "MZ",
    "MM",
    "NA",
    "NR",
    "NP",
    "NL",
    "NC",
    "NZ",
    "NI",
    "NE",
    "NG",
    "NU",
    "NF",
    "MP",
    "NO",
    "OM",
    "PK",
    "PW",
    "PA",
    "PG",
    "PY",
    "PE",
    "PH",
    "PN",
    "PL",
    "PT",
    "PR",
    "QA",
    "KR",
    "RS",
    "SC",
    "CG",
    "RE",
    "RO",
    "RU",
    "RW",
    "BL",
    "SH",
    "KN",
    "LC",
    "MF",
    "PM",
    "VC",
    "WS",
    "SM",
    "ST",
    "SA",
    "SN",
    "SL",
    "SG",
    "SX",
    "SK",
    "SI",
    "SB",
    "SO",
    "ZA",
    "GS",
    "SS",
    "ES",
    "LK",
    "PS",
    "SR",
    "SJ",
    "SE",
    "CH",
    "TW",
    "TJ",
    "TZ",
    "TH",
    "TL",
    "TG",
    "TK",
    "TO",
    "TT",
    "TN",
    "TR",
    "TM",
    "TC",
    "TV",
    "UG",
    "UA",
    "AE",
    "GB",
    "US",
    "UY",
    "UZ",
    "VU",
    "VA",
    "VE",
    "VN",
    "VG",
    "VI",
    "WF",
    "EH",
    "YE",
    "ZM",
    "ZW",
]

ModelLiteral = Literal[
    "UF-Nano",
    "UF-Loco",
    "UF-Wifi",
    "UF-Instant",
    "UF-Wifi6",
    "UISP-FIBER-XG",
    "UISP-FIBER-XGS",
    "UF-OLT",
    "UF-OLT4",
    "UISP-FIBER-OLT-XGS",
    "UISP-R-LXC-24",
    "UISP-R-Pro",
    "UISP-Console",
    "UISP-R-Lite",
    "UISP-R",
    "UISP-R-Plus",
    "UNMS-S-Lite",
    "UISP-S-Lite",
    "UISP-S-Pro",
    "UISP-S",
    "UISP-S-Plus",
    "UISP-LTE",
    "UISP-LTE-EU",
    "UISP-LTE-US",
    "ER-X",
    "ER-X-SFP",
    "ERLite-3",
    "ERPoe-5",
    "ERPro-8",
    "ER-8",
    "ER-8-XG",
    "ER-4",
    "ER-6P",
    "ER-12",
    "ER-12P",
    "ER-10X",
    "EP-R8",
    "EP-R6",
    "EP-S16",
    "ES-12F",
    "ES-16-150W",
    "ES-24-250W",
    "ES-24-500W",
    "ES-24-Lite",
    "ES-48-500W",
    "ES-48-750W",
    "ES-48-Lite",
    "ES-8-150W",
    "ES-16-XG",
    "ES-10XP",
    "ES-10X",
    "ES-18X",
    "ES-26X",
    "EP-54V-150W",
    "EP-24V-72W",
    "EP-54V-72W",
    "UISP-P",
    "UISP-P-Pro",
    "TSW-PoE",
    "TSW-PoE PRO",
    "ACB-AC",
    "ACB-ISP",
    "ACB-LOCO",
    "AF11FX",
    "AF24",
    "AF24HD",
    "AF2X",
    "AF3X",
    "AF4X",
    "AF5",
    "AF5U",
    "AF5X",
    "AF-5XHD",
    "AF-LTU",
    "LTU-Lite",
    "AF-LTU5",
    "LTU-Rocket",
    "LTU-LR",
    "LTU-XR",
    "LTU-Instant",
    "AF60",
    "AF60-LR",
    "AF60XG",
    "AF60HD",
    "AF60-XR",
    "Wave-AP",
    "WaveAP",
    "Wave-LR",
    "Wave-Nano",
    "Wave-AP-Micro",
    "Wave-Pro",
    "Wave-Pico",
    "GBE-LR",
    "GBE",
    "GBE-Plus",
    "GBE-AP",
    "R2N",
    "R2T",
    "R5N",
    "R6N",
    "R36-GPS",
    "RM3-GPS",
    "R2N-GPS",
    "R5N-GPS",
    "R9N-GPS",
    "R5T-GPS",
    "RM3",
    "R36",
    "R9N",
    "N2N",
    "N5N",
    "N6N",
    "NS3",
    "N36",
    "N9N",
    "N9S",
    "LM2",
    "LM5",
    "B2N",
    "B2T",
    "B5N",
    "B5T",
    "BAC",
    "AG2",
    "AG2-HP",
    "AG5",
    "AG5-HP",
    "p2N",
    "p5N",
    "M25",
    "P2B-400",
    "P5B-300",
    "P5B-300-ISO",
    "P5B-400",
    "P5B-400-ISO",
    "P5B-620",
    "LB5-120",
    "LB5",
    "N5B",
    "N5B-16",
    "N5B-19",
    "N5B-300",
    "N5B-400",
    "N5B-Client",
    "N2B",
    "N2B-13",
    "N2B-400",
    "PAP",
    "LAP-HP",
    "LAP",
    "AGW",
    "AGW-LR",
    "AGW-Pro",
    "AGW-Installer",
    "PB5",
    "PB3",
    "P36",
    "PBM10",
    "NB5",
    "NB2",
    "NB3",
    "B36",
    "NB9",
    "SM5",
    "WM5",
    "IS-M5",
    "Loco5AC",
    "NS-5AC",
    "R5AC-PTMP",
    "R5AC-PTP",
    "R5AC-Lite",
    "R5AC-PRISM",
    "R2AC-Prism",
    "R2AC-Gen2",
    "RP-5AC-Gen2",
    "NBE-2AC-13",
    "NBE-5AC-16",
    "NBE-5AC-19",
    "NBE-5AC-Gen2",
    "PBE-5AC-300",
    "PBE-5AC-300-ISO",
    "PBE-5AC-400",
    "PBE-5AC-400-ISO",
    "PBE-5AC-500",
    "PBE-5AC-500-ISO",
    "PBE-5AC-620",
    "PBE-5AC-620-ISO",
    "PBE-2AC-400",
    "PBE-2AC-400-ISO",
    "PBE-5AC-X-Gen2",
    "PBE-5AC-Gen2",
    "PBE-5AC-ISO-Gen2",
    "PBE-5AC-400-ISO-Gen2",
    "LBE-5AC-16-120",
    "LAP-120",
    "LBE-5AC-23",
    "LBE-5AC-Gen2",
    "LBE-5AC-LR",
    "LBE-5AC-XR",
    "LBE-AX",
    "LAP-GPS",
    "IS-5AC",
    "PS-5AC",
    "PRI-AX",
    "PAX-OM",
    "SolarSwitch",
    "SolarPoint",
    "BulletAC-IP67",
    "B-DB-AC",
    "AFi-ALN-R",
    "UX",
    "UNKNOWN",
]


PlatformNameLiteral = Literal[
    "UISP Fiber NanoG",
    "UISP Fiber Loco",
    "UISP Fiber Wifi",
    "UISP Fiber Instant",
    "UISP Fiber Wifi6",
    "UISP Fiber XG",
    "UISP Fiber XGS",
    "UISP Router LXC",
    "UISPRPro",
    "UISPConsole",
    "UISPR",
    "UISPRPlus",
    "UISPS",
    "UISPSPlus",
    "UISPSPro",
    "UNMSS",
    "UISPLTE",
    "UISPLTEEU",
    "UISPLTEUS",
    "UISPP",
    "UISPFiberOltXgs",
    "e50",
    "e100",
    "e200",
    "e300",
    "e600",
    "e1000",
    "u50",
    "u100",
    "u200",
    "u300",
    "u1000",
    "ESWH",
    "ESGH",
    "ES",
    "ESX",
    "EP",
    "EPX",
    "SW",
    "ACB",
    "AFI",
    "WA",
    "2WA",
    "XC",
    "2XC",
    "XW",
    "XM",
    "TI",
    "GBE",
    "RAX",
    "AirGW",
    "AirGWP",
    "AF",
    "AF02",
    "AF06",
    "AF07",
    "AF08",
    "AF09",
    "AF60",
    "af5xhd",
    "afltu",
    "afltu-ptp",
    "lturocket",
    "GP",
    "XR",
    "GMP",
    "MGMP",
    "GMC",
    "SunMax",
    "UX",
    "UNKNOWN",
]

RoleLiteral = Literal[
    "ap",
    "gateway",
    "gpon",
    "convertor",
    "other",
    "ptp",
    "router",
    "server",
    "station",
    "switch",
    "ups",
    "wireless",
    "wired",
    "homeWiFi",
    "wirelessDevice",
]

StatusLiteral = Literal[
    "active",
    "connecting",
    "discovered",
    "inactive",
    "disabled",
    "disconnected",
    "unauthorized",
    "proposed",
    "unknown",
    "unplaced",
    "custom",
    "maintenance",
    "incompatible",
    "unmonitored",
    "unassigned",
    "misconfigured",
    "preregistration",
]

DeviceTypeLiteral = Literal[
    "onu",
    "olt",
    "uispp",
    "uispr",
    "uisps",
    "uispLte",
    "erouter",
    "eswitch",
    "epower",
    "airCube",
    "airMax",
    "airFiber",
    "toughSwitch",
    "solarBeam",
    "wave",
    "blackBox",
    "uisprlxc",
    "express",
]
