# Generated by Django 4.2.9 on 2024-02-19 00:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import drf_hooks.models


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("meshapi_hooks", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="CelerySerializerHook",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
                ("event", models.CharField(db_index=True, max_length=64, verbose_name="Event")),
                ("target", models.URLField(max_length=255, verbose_name="Target URL")),
                ("headers", models.JSONField(default=drf_hooks.models.get_default_headers)),
                (
                    "enabled",
                    models.BooleanField(
                        default=True,
                        help_text="Should this webhook be used? This field be automatically changed by the system when too many consecutive failures are detected at the recipient",
                    ),
                ),
                (
                    "consecutive_failures",
                    models.IntegerField(
                        default=0,
                        help_text="The number of consecutive failures detected for this endpoint. This should not be modified by administrators",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)ss",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Webhook Target",
                "verbose_name_plural": "Webhook Targets",
            },
        ),
        migrations.RemoveField(
            model_name="recursiveserializerhook",
            name="user",
        ),
        migrations.DeleteModel(
            name="CeleryRecursiveSerializerHook",
        ),
        migrations.DeleteModel(
            name="RecursiveSerializerHook",
        ),
    ]
