VALID_ADDRESS_GEOCODE_RESPONSE = {
    "geocoding": {
        "version": "0.2",
        "attribution": "http://geosearch.planninglabs.nyc/attribution",
        "query": {
            "text": "151 Broome St, New York, NY 10002",
            "size": 1,
            "private": False,
            "lang": {"name": "English", "iso6391": "en", "iso6393": "eng", "via": "default", "defaulted": True},
            "querySize": 20,
            "parser": "pelias",
            "parsed_text": {
                "subject": "151 Broome St",
                "housenumber": "151",
                "street": "Broome St",
                "locality": "New York",
                "region": "NY",
                "postcode": "10002",
                "admin": "New York, NY",
            },
        },
        "engine": {"name": "Pelias", "author": "Mapzen", "version": "1.0"},
        "timestamp": 1722806729739,
    },
    "type": "FeatureCollection",
    "features": [
        {
            "type": "Feature",
            "geometry": {"type": "Point", "coordinates": [-73.98492, 40.716245]},
            "properties": {
                "id": "26676",
                "gid": "nycpad:venue:26676",
                "layer": "venue",
                "source": "nycpad",
                "source_id": "26676",
                "country_code": "US",
                "name": "151 BROOME STREET",
                "housenumber": "151",
                "street": "BROOME STREET",
                "postalcode": "10002",
                "confidence": 0.8,
                "match_type": "fallback",
                "accuracy": "point",
                "country": "United States",
                "country_gid": "whosonfirst:country:85633793",
                "country_a": "USA",
                "region": "New York",
                "region_gid": "whosonfirst:region:85688543",
                "region_a": "NY",
                "county": "New York County",
                "county_gid": "whosonfirst:county:102081863",
                "locality": "New York",
                "locality_gid": "whosonfirst:locality:85977539",
                "locality_a": "NYC",
                "borough": "Manhattan",
                "borough_gid": "whosonfirst:borough:421205771",
                "neighbourhood": "Lower East Side",
                "neighbourhood_gid": "whosonfirst:neighbourhood:85831563",
                "label": "151 BROOME STREET, New York, NY, USA",
                "addendum": {"pad": {"bbl": "1003410062", "bin": "1077609", "version": "24b"}},
            },
        }
    ],
    "bbox": [-73.98492, 40.716245, -73.98492, 40.716245],
}

INVALID_ADDRESS_GEOCODE_RESPONSE = {
    "geocoding": {
        "version": "0.2",
        "attribution": "http://geosearch.planninglabs.nyc/attribution",
        "query": {
            "text": "12341 Whackadoole Ave, New York, NY 10002",
            "size": 1,
            "private": False,
            "lang": {"name": "English", "iso6391": "en", "iso6393": "eng", "via": "default", "defaulted": True},
            "querySize": 20,
            "parser": "pelias",
            "parsed_text": {
                "subject": "12341 Whackadoole Ave",
                "housenumber": "12341",
                "street": "Whackadoole Ave",
                "locality": "New York",
                "region": "NY",
                "postcode": "10002",
                "admin": "New York, NY",
            },
        },
        "engine": {"name": "Pelias", "author": "Mapzen", "version": "1.0"},
        "timestamp": 1722806978411,
    },
    "type": "FeatureCollection",
    "features": [
        {
            "type": "Feature",
            "geometry": {"type": "Point", "coordinates": [-73.827527, 40.709085]},
            "properties": {
                "id": "2461559",
                "gid": "nycpad:venue:2461559",
                "layer": "venue",
                "source": "nycpad",
                "source_id": "2461559",
                "country_code": "US",
                "name": "12341 84 AVENUE",
                "housenumber": "12341",
                "street": "84 AVENUE",
                "postalcode": "11415",
                "confidence": 0.8,
                "match_type": "fallback",
                "accuracy": "point",
                "country": "United States",
                "country_gid": "whosonfirst:country:85633793",
                "country_a": "USA",
                "region": "New York",
                "region_gid": "whosonfirst:region:85688543",
                "region_a": "NY",
                "county": "Queens County",
                "county_gid": "whosonfirst:county:102082377",
                "locality": "New York",
                "locality_gid": "whosonfirst:locality:85977539",
                "locality_a": "NYC",
                "borough": "Queens",
                "borough_gid": "whosonfirst:borough:421205767",
                "neighbourhood": "Kew Gardens",
                "neighbourhood_gid": "whosonfirst:neighbourhood:420529695",
                "label": "12341 84 AVENUE, Kew Gardens, NY, USA",
                "addendum": {"pad": {"bbl": "4033560023", "bin": "4433895", "version": "24b"}},
            },
        }
    ],
    "bbox": [-73.827527, 40.709085, -73.827527, 40.709085],
}

VALID_BUILDING_HEIGHT_RESPONSE = [{"ground_elevation": "26", "height_roof": "14.58"}]
