# Generated by Django 4.2.9 on 2024-01-20 09:37

import django.contrib.auth.models
import django.contrib.postgres.fields
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.CreateModel(
            name="Admin",
            fields=[
                (
                    "group_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="auth.group",
                    ),
                ),
                ("description", models.TextField(blank=True, max_length=100)),
            ],
            bases=("auth.group",),
            managers=[
                ("objects", django.contrib.auth.models.GroupManager()),
            ],
        ),
        migrations.CreateModel(
            name="Building",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("bin", models.IntegerField(blank=True, null=True)),
                ("building_status", models.IntegerField(choices=[(0, "Inactive"), (1, "Active")])),
                ("street_address", models.TextField(blank=True, null=True)),
                ("city", models.TextField(blank=True, null=True)),
                ("state", models.TextField(blank=True, null=True)),
                ("zip_code", models.TextField(blank=True, null=True)),
                ("invalid", models.BooleanField(default=False)),
                ("address_truth_sources", models.TextField()),
                ("latitude", models.FloatField()),
                ("longitude", models.FloatField()),
                ("altitude", models.FloatField(blank=True, null=True)),
                (
                    "primary_nn",
                    models.IntegerField(
                        blank=True,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(101),
                            django.core.validators.MaxValueValidator(8192),
                        ],
                    ),
                ),
                ("node_name", models.TextField(blank=True, default=None, null=True)),
                ("notes", models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="Installer",
            fields=[
                (
                    "group_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="auth.group",
                    ),
                ),
                ("description", models.TextField(blank=True, max_length=100)),
            ],
            bases=("auth.group",),
            managers=[
                ("objects", django.contrib.auth.models.GroupManager()),
            ],
        ),
        migrations.CreateModel(
            name="Member",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.TextField()),
                ("email_address", models.EmailField(max_length=254, null=True)),
                (
                    "secondary_emails",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.EmailField(max_length=254), null=True, size=None
                    ),
                ),
                ("phone_number", models.TextField(blank=True, default=None, null=True)),
                ("slack_handle", models.TextField(blank=True, default=None, null=True)),
                ("invalid", models.BooleanField(default=False)),
                ("contact_notes", models.TextField(blank=True, default=None, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="ReadOnly",
            fields=[
                (
                    "group_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="auth.group",
                    ),
                ),
                ("description", models.TextField(blank=True, max_length=100)),
            ],
            bases=("auth.group",),
            managers=[
                ("objects", django.contrib.auth.models.GroupManager()),
            ],
        ),
        migrations.CreateModel(
            name="Sector",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.TextField()),
                ("radius", models.FloatField(validators=[django.core.validators.MinValueValidator(0)])),
                (
                    "azimuth",
                    models.IntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(360),
                        ]
                    ),
                ),
                (
                    "width",
                    models.IntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(360),
                        ]
                    ),
                ),
                (
                    "status",
                    models.TextField(
                        choices=[("Abandoned", "Abandoned"), ("Active", "Active"), ("Potential", "Potential")]
                    ),
                ),
                ("install_date", models.DateField(blank=True, default=None, null=True)),
                ("abandon_date", models.DateField(blank=True, default=None, null=True)),
                ("device_name", models.TextField()),
                ("ssid", models.TextField(blank=True, default=None, null=True)),
                ("notes", models.TextField(blank=True, default=None, null=True)),
                ("building", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to="meshapi.building")),
            ],
        ),
        migrations.CreateModel(
            name="Link",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("status", models.TextField(choices=[("Dead", "Dead"), ("Planned", "Planned"), ("Active", "Active")])),
                (
                    "type",
                    models.TextField(
                        blank=True,
                        choices=[("Standard", "Standard"), ("VPN", "Vpn"), ("MMWave", "Mmwave"), ("Fiber", "Fiber")],
                        default=None,
                        null=True,
                    ),
                ),
                ("install_date", models.DateField(blank=True, default=None, null=True)),
                ("abandon_date", models.DateField(blank=True, default=None, null=True)),
                ("description", models.TextField(blank=True, default=None, null=True)),
                ("notes", models.TextField(blank=True, default=None, null=True)),
                (
                    "from_building",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, related_name="link_from", to="meshapi.building"
                    ),
                ),
                (
                    "to_building",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, related_name="link_to", to="meshapi.building"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Install",
            fields=[
                ("install_number", models.AutoField(db_column="install_number", primary_key=True, serialize=False)),
                (
                    "network_number",
                    models.IntegerField(
                        blank=True,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(101),
                            django.core.validators.MaxValueValidator(8192),
                        ],
                    ),
                ),
                (
                    "install_status",
                    models.IntegerField(
                        choices=[
                            (0, "Open"),
                            (1, "Scheduled"),
                            (2, "Nn Assigned"),
                            (3, "Blocked"),
                            (4, "Active"),
                            (5, "Inactive"),
                            (6, "Closed"),
                        ]
                    ),
                ),
                ("ticket_id", models.IntegerField(blank=True, null=True)),
                ("request_date", models.DateField()),
                ("install_date", models.DateField(blank=True, default=None, null=True)),
                ("abandon_date", models.DateField(blank=True, default=None, null=True)),
                ("unit", models.TextField(blank=True, default=None, null=True)),
                ("roof_access", models.BooleanField(default=False)),
                ("referral", models.TextField(blank=True, default=None, null=True)),
                ("notes", models.TextField(blank=True, default=None, null=True)),
                ("building", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to="meshapi.building")),
                ("member", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to="meshapi.member")),
            ],
        ),
    ]
