# Generated by Django 4.2.5 on 2023-12-24 21:51

import django.contrib.auth.models
import django.contrib.postgres.fields
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


# Functions from the following migrations need manual copying.
# Move them and any dependencies into this file, then update the
# RunPython operations to refer to the local versions:
# meshapi.migrations.0016_create_default_groups

class Migration(migrations.Migration):

    replaces = [('meshapi', '0001_squashed_0015_alter_building_bin'), ('meshapi', '0016_create_default_groups'), ('meshapi', '0017_building_node_name_building_secondary_nn_and_more'), ('meshapi', '0018_rename_network_number_building_primary_nn_and_more'), ('meshapi', '0019_alter_install_install_number'), ('meshapi', '0020_alter_install_install_number'), ('meshapi', '0021_alter_install_install_number_and_more'), ('meshapi', '0022_alter_building_abandon_date_and_more')]

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Building',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bin', models.IntegerField()),
                ('building_status', models.IntegerField(choices=[(0, 'Inactive'), (1, 'Active')])),
                ('street_address', models.TextField()),
                ('city', models.TextField()),
                ('state', models.TextField()),
                ('zip_code', models.IntegerField()),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('altitude', models.FloatField()),
                ('network_number', models.IntegerField(blank=True, null=True)),
                ('install_date', models.DateField(blank=True, default=None, null=True)),
                ('abandon_date', models.DateField(blank=True, default=None, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.TextField()),
                ('last_name', models.TextField()),
                ('email_address', models.EmailField(max_length=254)),
                ('phone_number', models.TextField(blank=True, default=None, null=True)),
                ('slack_handle', models.TextField(blank=True, default=None, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Install',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('install_number', models.IntegerField()),
                ('install_status', models.IntegerField(choices=[(0, 'Planned'), (1, 'Inactive'), (2, 'Active')])),
                ('building_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='meshapi.building')),
                ('member_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='meshapi.member')),
                ('abandon_date', models.DateField(blank=True, default=None, null=True)),
                ('install_date', models.DateField(blank=True, default=None, null=True)),
                ('unit', models.TextField(blank=True, default=None, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Installer',
            fields=[
                ('group_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='auth.group')),
                ('description', models.TextField(blank=True, max_length=100)),
            ],
            bases=('auth.group',),
            managers=[
                ('objects', django.contrib.auth.models.GroupManager()),
            ],
        ),
        migrations.CreateModel(
            name='Request',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_status', models.IntegerField(choices=[(0, 'Open'), (1, 'Closed'), (2, 'Installed')])),
                ('ticket_id', models.IntegerField(blank=True, null=True)),
                ('building_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='meshapi.building')),
                ('install_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='meshapi.install')),
                ('member_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='meshapi.member')),
                ('roof_access', models.BooleanField(default=False)),
                ('referral', models.TextField(blank=True, default=None, null=True)),
                ('unit', models.TextField(blank=True, default=None, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='building',
            name='node_name',
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='install',
            name='notes',
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='install',
            name='request_date',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='install',
            name='roof_access',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='install',
            name='ticket_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='member',
            name='secondary_emails',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.EmailField(max_length=254), null=True, size=None),
        ),
        migrations.AlterField(
            model_name='install',
            name='install_status',
            field=models.IntegerField(choices=[(0, 'Open'), (1, 'Scheduled'), (2, 'Blocked'), (3, 'Active'), (4, 'Inactive'), (5, 'Closed')]),
        ),
        migrations.DeleteModel(
            name='Request',
        ),
        migrations.RenameField(
            model_name='building',
            old_name='network_number',
            new_name='primary_nn',
        ),
        migrations.RemoveField(
            model_name='install',
            name='id',
        ),
        migrations.AlterField(
            model_name='install',
            name='install_number',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='install',
            name='install_number',
            field=models.AutoField(db_column='install_number', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='install',
            name='install_number',
            field=models.AutoField(db_column='install_number', primary_key=True, serialize=False, validators=[django.core.validators.MinValueValidator(101), django.core.validators.MaxValueValidator(8192)]),
        ),
        migrations.AlterField(
            model_name='install',
            name='install_number',
            field=models.AutoField(db_column='install_number', primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name='install',
            name='network_number',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(101), django.core.validators.MaxValueValidator(8192)]),
        ),
        migrations.AlterField(
            model_name='building',
            name='abandon_date',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='building',
            name='install_date',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='install',
            name='abandon_date',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='install',
            name='install_date',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
    ]
