# Generated by Django 4.2.9 on 2024-01-28 01:02

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("meshapi", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="installer",
            name="group_ptr",
        ),
        migrations.RemoveField(
            model_name="readonly",
            name="group_ptr",
        ),
        migrations.DeleteModel(
            name="Admin",
        ),
        migrations.DeleteModel(
            name="Installer",
        ),
        migrations.DeleteModel(
            name="ReadOnly",
        ),
    ]
