# Generated by Django 4.2.9 on 2024-01-20 07:46

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("meshapi", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="building",
            name="primary_nn",
            field=models.IntegerField(
                blank=True,
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(101),
                    django.core.validators.MaxValueValidator(8192),
                ],
            ),
        ),
        migrations.CreateModel(
            name="Sector",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.TextField()),
                ("radius", models.FloatField(validators=[django.core.validators.MinValueValidator(0)])),
                (
                    "azimuth",
                    models.IntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(360),
                        ]
                    ),
                ),
                (
                    "width",
                    models.IntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(360),
                        ]
                    ),
                ),
                ("status", models.TextField(choices=[("Abandoned", "Abandoned"), ("Active", "Active")])),
                ("install_date", models.DateField(blank=True, default=None, null=True)),
                ("abandon_date", models.DateField(blank=True, default=None, null=True)),
                ("device_name", models.TextField()),
                ("ssid", models.TextField(blank=True, default=None, null=True)),
                ("notes", models.TextField(blank=True, default=None, null=True)),
                ("building", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to="meshapi.building")),
            ],
        ),
        migrations.CreateModel(
            name="Link",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("status", models.TextField(choices=[("Dead", "Dead"), ("Planned", "Planned"), ("Active", "Active")])),
                (
                    "type",
                    models.TextField(
                        choices=[("Standard", "Standard"), ("VPN", "Vpn"), ("MMWave", "Mmwave"), ("Fiber", "Fiber")]
                    ),
                ),
                ("install_date", models.DateField(blank=True, default=None, null=True)),
                ("abandon_date", models.DateField(blank=True, default=None, null=True)),
                ("description", models.TextField(blank=True, default=None, null=True)),
                ("notes", models.TextField(blank=True, default=None, null=True)),
                (
                    "from_building",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, related_name="link_from", to="meshapi.building"
                    ),
                ),
                (
                    "to_building",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, related_name="link_to", to="meshapi.building"
                    ),
                ),
            ],
        ),
    ]
