# Generated by Django 4.2.9 on 2024-01-14 01:30

from django.db import migrations, models


class Migration(migrations.Migration):
    replaces = [
        ("meshapi", "0002_member_contact_notes_member_invalid"),
        ("meshapi", "0003_alter_member_email_address"),
        ("meshapi", "0004_building_apartment_number"),
        ("meshapi", "0005_building_invalid_alter_building_city_and_more"),
        ("meshapi", "0006_building_address_truth_sources"),
        ("meshapi", "0007_remove_building_apartment_number"),
        ("meshapi", "0008_building_notes"),
        ("meshapi", "0009_alter_building_zip_code"),
        ("meshapi", "0010_alter_building_bin"),
        ("meshapi", "0011_alter_building_altitude"),
        ("meshapi", "0012_rename_building_id_install_building_and_more"),
    ]

    dependencies = [
        ("meshapi", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="member",
            name="contact_notes",
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name="member",
            name="invalid",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="member",
            name="email_address",
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.AddField(
            model_name="building",
            name="invalid",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="building",
            name="city",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="building",
            name="state",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="building",
            name="street_address",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="building",
            name="zip_code",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="building",
            name="address_truth_sources",
            field=models.TextField(default=""),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="building",
            name="notes",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="building",
            name="zip_code",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="building",
            name="bin",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="building",
            name="altitude",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.RenameField(
            model_name="install",
            old_name="building_id",
            new_name="building",
        ),
        migrations.RenameField(
            model_name="install",
            old_name="member_id",
            new_name="member",
        ),
        migrations.AlterField(
            model_name="install",
            name="request_date",
            field=models.DateField(),
        ),
    ]
