# Generated by Django 4.2.16 on 2024-11-22 19:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("meshapi", "0002_create_meshdb_ro"),
    ]

    operations = [
        migrations.AlterField(
            model_name="historicalinstall",
            name="request_date",
            field=models.DateTimeField(help_text="The date and time that this install request was received"),
        ),
        migrations.AlterField(
            model_name="install",
            name="request_date",
            field=models.DateTimeField(help_text="The date and time that this install request was received"),
        ),
    ]
