# Generated by Django 4.2.11 on 2024-03-22 01:45

import django_jsonform.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("meshapi", "0002_remove_sector_ssid_device_ssid_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="install",
            options={
                "permissions": [
                    ("assign_nn", "Can assign an NN to install"),
                    ("update_panoramas", "Can update panoramas"),
                ]
            },
        ),
        migrations.AddField(
            model_name="building",
            name="panoramas",
            field=django_jsonform.models.fields.ArrayField(
                base_field=models.URLField(),
                blank=True,
                default=list,
                help_text="Panoramas taken from the roof of this Building",
                null=True,
                size=None,
            ),
        ),
        migrations.AlterField(
            model_name="member",
            name="additional_email_addresses",
            field=django_jsonform.models.fields.ArrayField(
                base_field=models.EmailField(max_length=254),
                blank=True,
                default=list,
                help_text="Any additional email addresses associated with this member",
                null=True,
                size=None,
            ),
        ),
    ]
