# Generated by Django 4.2.9 on 2024-01-28 02:49

from django.db import migrations, models


def migrate_building_status_int_to_str(apps, _):
    Building = apps.get_model("meshapi", "Building")

    old_to_new_status_mapping = {0: "Inactive", 1: "Active"}

    for building in Building.objects.all():
        building.building_status = old_to_new_status_mapping[building.building_status_old]
        building.save()


def migrate_install_status_int_to_str(apps, _):
    Install = apps.get_model("meshapi", "Install")

    old_to_new_status_mapping = {
        0: "Open",
        1: "Scheduled",
        2: "NN Assigned",
        3: "Blocked",
        4: "Active",
        5: "Inactive",
        6: "Closed",
    }

    for install in Install.objects.all():
        install.install_status = old_to_new_status_mapping[install.install_status_old]
        install.save()


class Migration(migrations.Migration):
    dependencies = [
        ("meshapi", "0002_remove_installer_group_ptr_remove_readonly_group_ptr_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="building",
            old_name="building_status",
            new_name="building_status_old",
        ),
        migrations.AddField(
            model_name="building",
            name="building_status",
            field=models.TextField(choices=[("Inactive", "Inactive"), ("Active", "Active")], default="Inactive"),
        ),
        migrations.RunPython(migrate_building_status_int_to_str),
        migrations.RemoveField(
            model_name="building",
            name="building_status_old",
        ),
        migrations.RenameField(
            model_name="install",
            old_name="install_status",
            new_name="install_status_old",
        ),
        migrations.AddField(
            model_name="install",
            name="install_status",
            field=models.TextField(
                choices=[
                    ("Open", "Open"),
                    ("Scheduled", "Scheduled"),
                    ("NN Assigned", "Nn Assigned"),
                    ("Blocked", "Blocked"),
                    ("Active", "Active"),
                    ("Inactive", "Inactive"),
                    ("Closed", "Closed"),
                ],
                default="Inactive",
            ),
        ),
        migrations.RunPython(migrate_install_status_int_to_str),
        migrations.RemoveField(
            model_name="install",
            name="install_status_old",
        ),
    ]
