# Generated by Django 4.2.15 on 2024-11-03 00:22

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("meshapi", "0002_create_meshdb_ro"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Permission",
        ),
    ]
