# Generated by Django 4.2.9 on 2024-01-20 09:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("meshapi", "0002_alter_building_primary_nn_sector_link"),
    ]

    operations = [
        migrations.AlterField(
            model_name="link",
            name="type",
            field=models.TextField(
                blank=True,
                choices=[("Standard", "Standard"), ("VPN", "Vpn"), ("MMWave", "Mmwave"), ("Fiber", "Fiber")],
                default=None,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="sector",
            name="status",
            field=models.TextField(
                choices=[("Abandoned", "Abandoned"), ("Active", "Active"), ("Potential", "Potential")]
            ),
        ),
    ]
