# Generated by Django 4.2.10 on 2024-03-30 00:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("meshapi", "0003_alter_install_options_building_panoramas_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="device",
            name="ip_address",
            field=models.GenericIPAddressField(
                blank=True,
                default=None,
                help_text="The IP address of this device within the 10.x network",
                null=True,
                protocol="ipv4",
            ),
        ),
    ]
