# Generated by Django 4.2.5 on 2023-09-21 01:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("meshapi", "0001_squashed_0003_alter_request_install_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="request",
            name="roof_access",
            field=models.BooleanField(default=False),
        ),
    ]
