# Generated by Django 4.2.17 on 2025-01-07 00:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("meshapi", "0003_alter_historicalinstall_request_date_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="historicalinstall",
            name="status",
            field=models.CharField(
                choices=[
                    ("Request Received", "Request Received"),
                    ("Pending", "Pending"),
                    ("Blocked", "Blocked"),
                    ("Active", "Active"),
                    ("Inactive", "Inactive"),
                    ("Closed", "Closed"),
                    ("NN Reassigned", "NN Reassigned"),
                ],
                help_text="The current status of this install",
            ),
        ),
        migrations.AlterField(
            model_name="historicallink",
            name="type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("5 GHz", "5 GHz"),
                    ("24 GHz", "24 GHz"),
                    ("60 GHz", "60 GHz"),
                    ("70-80 GHz", "70-80 GHz"),
                    ("VPN", "VPN"),
                    ("Fiber", "Fiber"),
                    ("Ethernet", "Ethernet"),
                ],
                default=None,
                help_text="The technology used for this link 5Ghz, 60Ghz, fiber, etc.",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="historicalnode",
            name="type",
            field=models.CharField(
                choices=[
                    ("Standard", "Standard"),
                    ("Hub", "Hub"),
                    ("Supernode", "Supernode"),
                    ("POP", "POP"),
                    ("AP", "AP"),
                    ("Remote", "Remote"),
                ],
                default="Standard",
                help_text="The type of node this is, controls the icon used on the network map",
            ),
        ),
        migrations.AlterField(
            model_name="install",
            name="status",
            field=models.CharField(
                choices=[
                    ("Request Received", "Request Received"),
                    ("Pending", "Pending"),
                    ("Blocked", "Blocked"),
                    ("Active", "Active"),
                    ("Inactive", "Inactive"),
                    ("Closed", "Closed"),
                    ("NN Reassigned", "NN Reassigned"),
                ],
                help_text="The current status of this install",
            ),
        ),
        migrations.AlterField(
            model_name="link",
            name="type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("5 GHz", "5 GHz"),
                    ("24 GHz", "24 GHz"),
                    ("60 GHz", "60 GHz"),
                    ("70-80 GHz", "70-80 GHz"),
                    ("VPN", "VPN"),
                    ("Fiber", "Fiber"),
                    ("Ethernet", "Ethernet"),
                ],
                default=None,
                help_text="The technology used for this link 5Ghz, 60Ghz, fiber, etc.",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="node",
            name="type",
            field=models.CharField(
                choices=[
                    ("Standard", "Standard"),
                    ("Hub", "Hub"),
                    ("Supernode", "Supernode"),
                    ("POP", "POP"),
                    ("AP", "AP"),
                    ("Remote", "Remote"),
                ],
                default="Standard",
                help_text="The type of node this is, controls the icon used on the network map",
            ),
        ),
    ]
