# Generated by Django 4.2.17 on 2024-12-24 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("meshapi", "0003_alter_historicalinstall_request_date_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="historicalnode",
            name="type",
            field=models.CharField(
                choices=[
                    ("Standard", "Standard"),
                    ("Hub", "Hub"),
                    ("Fiber Connected Hub", "Fiber Hub"),
                    ("Supernode", "Supernode"),
                    ("POP", "Pop"),
                    ("AP", "Ap"),
                    ("Remote", "Remote"),
                ],
                default="Standard",
                help_text="The type of node this is, controls the icon used on the network map",
            ),
        ),
        migrations.AlterField(
            model_name="node",
            name="type",
            field=models.CharField(
                choices=[
                    ("Standard", "Standard"),
                    ("Hub", "Hub"),
                    ("Fiber Connected Hub", "Fiber Hub"),
                    ("Supernode", "Supernode"),
                    ("POP", "Pop"),
                    ("AP", "Ap"),
                    ("Remote", "Remote"),
                ],
                default="Standard",
                help_text="The type of node this is, controls the icon used on the network map",
            ),
        ),
    ]
