# Generated by Django 4.2.9 on 2024-01-29 04:29

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("meshapi", "0003_alter_building_building_status_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="install",
            options={"permissions": [("assign_nn", "Can assign an NN to install")]},
        ),
    ]
