# Generated by Django 4.2.19 on 2025-03-11 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("meshapi", "0004_alter_historicalinstall_status_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="install",
            name="additional_members",
            field=models.ManyToManyField(
                blank=True,
                help_text="Any additional members associated with this install. E.g. roommates, parents, caretakers etc. Anyone that might contact us on behalf of this install belongs here",
                related_name="additional_installs",
                to="meshapi.member",
            ),
        ),
    ]
