# Generated by Django 4.2.17 on 2025-01-07 04:05

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("meshapi", "0004_alter_historicalinstall_status_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="historicalnode",
            name="network_number",
            field=models.IntegerField(
                blank=True, db_index=True, null=True, validators=[django.core.validators.MaxValueValidator(8000)]
            ),
        ),
        migrations.AlterField(
            model_name="node",
            name="network_number",
            field=models.IntegerField(
                blank=True, null=True, unique=True, validators=[django.core.validators.MaxValueValidator(8000)]
            ),
        ),
    ]
