# Generated by Django 4.2.19 on 2025-03-09 00:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("meshapi", "0004_alter_historicalinstall_status_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="install",
            name="additional_members",
            field=models.ManyToManyField(
                help_text="Any additional members associated with this install",
                related_name="additional_installs",
                to="meshapi.member",
            ),
        ),
    ]
