# Generated by Django 4.2.17 on 2024-12-24 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("meshapi", "0004_alter_historicalnode_type_alter_node_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="historicallink",
            name="map_display_override",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Hidden", "Hidden"),
                    ("Planned", "Planned"),
                    ("Yellow", "Yellow"),
                    ("Light Blue", "Light Blue"),
                    ("Dark Blue", "Dark Blue"),
                    ("Purple", "Purple"),
                ],
                default=None,
                help_text="Optional configuration to force specific map display for this link, regardless of the actual type/status. This should not be used for most links",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="link",
            name="map_display_override",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Hidden", "Hidden"),
                    ("Planned", "Planned"),
                    ("Yellow", "Yellow"),
                    ("Light Blue", "Light Blue"),
                    ("Dark Blue", "Dark Blue"),
                    ("Purple", "Purple"),
                ],
                default=None,
                help_text="Optional configuration to force specific map display for this link, regardless of the actual type/status. This should not be used for most links",
                null=True,
            ),
        ),
    ]
