# Generated by Django 4.2.5 on 2023-09-24 15:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("meshapi", "0004_request_roof_access"),
    ]

    operations = [
        migrations.AddField(
            model_name="install",
            name="unit",
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name="request",
            name="referral",
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name="request",
            name="unit",
            field=models.TextField(blank=True, default=None, null=True),
        ),
    ]
