# Generated by Django 4.2.9 on 2024-01-31 06:33

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("meshapi", "0005_alter_install_install_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="member",
            name="stripe_email_address",
            field=models.EmailField(blank=True, default=None, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name="member",
            name="secondary_emails",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.EmailField(max_length=254), blank=True, default=list, null=True, size=None
            ),
        ),
    ]
