# Generated by Django 4.2.5 on 2023-09-24 15:34

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("meshapi", "0005_install_unit_request_referral_request_unit"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="request",
            name="unit",
        ),
    ]
