# Generated by Django 4.2.19 on 2025-03-09 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("meshapi", "0005_install_additional_members"),
    ]

    operations = [
        migrations.AlterField(
            model_name="install",
            name="additional_members",
            field=models.ManyToManyField(
                blank=True,
                help_text="Any additional members associated with this install",
                related_name="additional_installs",
                to="meshapi.member",
            ),
        ),
    ]
