# Generated by Django 4.2.9 on 2024-01-31 05:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("meshapi", "0005_alter_install_install_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="member",
            name="stripe_email_address",
            field=models.EmailField(max_length=254, null=True),
        ),
    ]
