# Generated by Django 4.2.17 on 2025-03-27 03:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import simple_history.models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("meshapi", "0006_install_additional_members"),
    ]

    operations = [
        migrations.CreateModel(
            name="InstallFeeBillingDatum",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("ToBeBilled", "To Be Billed"),
                            ("Billed", "Billed"),
                            ("NotBillingDuplicate", "Not Billing - Duplicate"),
                            ("NotBillingOther", "Not Billing - Other"),
                        ],
                        default="ToBeBilled",
                        help_text="The billing status of the associated install",
                    ),
                ),
                (
                    "billing_date",
                    models.DateField(
                        blank=True,
                        default=None,
                        help_text="The date that the associated install was billed to the responsible organization",
                        null=True,
                    ),
                ),
                (
                    "invoice_number",
                    models.CharField(
                        blank=True,
                        default=None,
                        help_text="The invoice number that the associated install was billed via",
                        null=True,
                    ),
                ),
                (
                    "notes",
                    models.TextField(
                        blank=True,
                        help_text="A free-form text description, to track any additional information.",
                        null=True,
                    ),
                ),
                (
                    "install",
                    models.OneToOneField(
                        help_text="Which Install object does this billing data refer to",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="install_fee_billing_datum",
                        to="meshapi.install",
                    ),
                ),
            ],
            options={
                "verbose_name": "Install Fee Billing Datum",
                "verbose_name_plural": "Install Fee Billing Data",
            },
        ),
        migrations.CreateModel(
            name="HistoricalInstallFeeBillingDatum",
            fields=[
                ("id", models.UUIDField(db_index=True, default=uuid.uuid4, editable=False)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("ToBeBilled", "To Be Billed"),
                            ("Billed", "Billed"),
                            ("NotBillingDuplicate", "Not Billing - Duplicate"),
                            ("NotBillingOther", "Not Billing - Other"),
                        ],
                        default="ToBeBilled",
                        help_text="The billing status of the associated install",
                    ),
                ),
                (
                    "billing_date",
                    models.DateField(
                        blank=True,
                        default=None,
                        help_text="The date that the associated install was billed to the responsible organization",
                        null=True,
                    ),
                ),
                (
                    "invoice_number",
                    models.CharField(
                        blank=True,
                        default=None,
                        help_text="The invoice number that the associated install was billed via",
                        null=True,
                    ),
                ),
                (
                    "notes",
                    models.TextField(
                        blank=True,
                        help_text="A free-form text description, to track any additional information.",
                        null=True,
                    ),
                ),
                ("history_id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")], max_length=1),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "install",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        help_text="Which Install object does this billing data refer to",
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="meshapi.install",
                    ),
                ),
            ],
            options={
                "verbose_name": "historical Install Fee Billing Datum",
                "verbose_name_plural": "historical Install Fee Billing Data",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
