# Generated by Django 4.2.9 on 2024-02-04 03:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("meshapi", "0006_member_stripe_email_address_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="install",
            name="building",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, related_name="installs", to="meshapi.building"
            ),
        ),
        migrations.AlterField(
            model_name="install",
            name="member",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, related_name="installs", to="meshapi.member"
            ),
        ),
    ]
