# Generated by Django 4.2.5 on 2023-09-24 20:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("meshapi", "0006_remove_request_unit"),
    ]

    operations = [
        migrations.AddField(
            model_name="request",
            name="unit",
            field=models.TextField(blank=True, default=None, null=True),
        ),
    ]
