# Generated by Django 4.2.10 on 2024-04-07 02:33

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("meshapi", "0006_alter_building_nodes_alter_building_primary_node_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="node",
            name="network_number",
            field=models.IntegerField(
                db_column="network_number",
                primary_key=True,
                serialize=False,
                validators=[django.core.validators.MaxValueValidator(8192)],
            ),
        ),
    ]
