# Generated by Django 4.2.5 on 2023-10-09 05:44

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("meshapi", "0005_alter_request_install_id"),
        ("meshapi", "0007_request_unit"),
    ]

    operations = []
