# Generated by Django 4.2.20 on 2025-04-21 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("meshapi", "0007_installfeebillingdatum_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="historicalnode",
            name="placement",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Rooftop", "Rooftop"),
                    ("Balcony", "Balcony"),
                    ("Window", "Window"),
                    ("Indoor", "Indoor (Fiber Sites, non-rooftop Supernodes, etc)"),
                ],
                help_text="The placement of this node within the building it is located on. Used to filter out balcony installs in some queries, such as when automatically determining if a join request can skip the panorama step of the intake process.",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="node",
            name="placement",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Rooftop", "Rooftop"),
                    ("Balcony", "Balcony"),
                    ("Window", "Window"),
                    ("Indoor", "Indoor (Fiber Sites, non-rooftop Supernodes, etc)"),
                ],
                help_text="The placement of this node within the building it is located on. Used to filter out balcony installs in some queries, such as when automatically determining if a join request can skip the panorama step of the intake process.",
                null=True,
            ),
        ),
    ]
