# Generated by Django 4.2.11 on 2024-04-21 23:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("meshapi", "0007_alter_node_network_number"),
    ]

    operations = [
        migrations.AlterField(
            model_name="building",
            name="notes",
            field=models.TextField(
                blank=True,
                help_text="A free-form text description of this building, to track any additional information. For Buidings imported from the spreadsheet, this starts with a formatted block of information about the import process and original spreadsheet data. However this structure can be changed by admins at any time and should not be relied on by automated systems. ",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="install",
            name="notes",
            field=models.TextField(
                blank=True,
                default=None,
                help_text="A free-form text description of this Install, to track any additional information. For Installs imported from the spreadsheet, this starts with a formatted block of information about the import process and original spreadsheet data. However this structure can be changed by admins at any time and should not be relied on by automated systems. ",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="member",
            name="notes",
            field=models.TextField(
                blank=True,
                default=None,
                help_text="A free-form text description of how to contact this member, to track any additional information. For Members imported from the spreadsheet, this starts with a formatted block of information about the import process and original spreadsheet data. However this structure can be changed by admins at any time and should not be relied on by automated systems. ",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="node",
            name="notes",
            field=models.TextField(
                blank=True,
                help_text="A free-form text description of this Node, to track any additional information. For Nodes imported from the spreadsheet, this starts with a formatted block of information about the import process and original spreadsheet data. However this structure can be changed by admins at any time and should not be relied on by automated systems. ",
                null=True,
            ),
        ),
    ]
