# Generated by Django 4.2.17 on 2025-04-23 00:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("meshapi", "0007_installfeebillingdatum_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="historicalinstall",
            name="stripe_subscription_id",
            field=models.CharField(
                blank=True,
                help_text="The Stripe.com Subscription ID for the monthly contributions associated with this install. The presence of a subscription id here does not imply an active subscription, to determine if a subscription is active, one must contact Stripe directly with this identifier",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="install",
            name="stripe_subscription_id",
            field=models.CharField(
                blank=True,
                help_text="The Stripe.com Subscription ID for the monthly contributions associated with this install. The presence of a subscription id here does not imply an active subscription, to determine if a subscription is active, one must contact Stripe directly with this identifier",
                null=True,
            ),
        ),
    ]
