# Generated by Django 4.2.10 on 2024-06-01 23:49

from django.db import migrations, models
import django_jsonform.models.fields


class Migration(migrations.Migration):
    dependencies = [
        ("meshapi", "0008_alter_building_notes_alter_install_notes_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="member",
            name="additional_phone_numbers",
            field=django_jsonform.models.fields.ArrayField(
                base_field=models.CharField(),
                blank=True,
                default=list,
                help_text="Any additional phone numbers used by this member",
                null=True,
                size=None,
            ),
        ),
        migrations.AlterField(
            model_name="member",
            name="phone_number",
            field=models.CharField(
                blank=True, default=None, help_text="A primary contact phone number for this member", null=True
            ),
        ),
    ]
