# Generated by Django 4.2.5 on 2023-10-13 06:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("meshapi", "0008_merge_0005_alter_request_install_id_0007_request_unit"),
    ]

    operations = [
        migrations.AlterField(
            model_name="building",
            name="id",
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID"),
        ),
        migrations.AlterField(
            model_name="install",
            name="id",
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID"),
        ),
        migrations.AlterField(
            model_name="member",
            name="id",
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID"),
        ),
        migrations.AlterField(
            model_name="request",
            name="id",
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID"),
        ),
    ]
