# Generated by Django 4.2.13 on 2024-06-20 22:26

from django.db import migrations, models

import meshapi.validation


class Migration(migrations.Migration):
    dependencies = [
        ("meshapi", "0008_alter_building_notes_alter_install_notes_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="member",
            name="phone_number",
            field=models.CharField(
                blank=True,
                default=None,
                help_text="A contact phone number for this member",
                null=True,
                validators=[meshapi.validation.validate_phone_number_field],
            ),
        ),
    ]
