# Generated by Django 4.2.9 on 2024-02-14 02:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("meshapi", "0008_install_diy"),
    ]

    operations = [
        migrations.AlterField(
            model_name="install",
            name="install_status",
            field=models.TextField(
                choices=[
                    ("Request Received", "Request Received"),
                    ("Pending", "Pending"),
                    ("Blocked", "Blocked"),
                    ("Active", "Active"),
                    ("Inactive", "Inactive"),
                    ("Closed", "Closed"),
                    ("NN Reassigned", "Nn Reassigned"),
                ]
            ),
        ),
    ]
