# Generated by Django 4.2.10 on 2024-02-16 01:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("meshapi", "0009_alter_install_install_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="link",
            name="from_building",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, related_name="links_from", to="meshapi.building"
            ),
        ),
        migrations.AlterField(
            model_name="link",
            name="to_building",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, related_name="links_to", to="meshapi.building"
            ),
        ),
        migrations.AlterField(
            model_name="sector",
            name="building",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, related_name="sectors", to="meshapi.building"
            ),
        ),
    ]
