# Generated by Django 4.2.19 on 2025-05-30 00:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("meshapi", "0009_alter_historicalnode_network_number_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="historicallink",
            name="type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("5 GHz", "5 GHz"),
                    ("6 GHz", "6 GHz"),
                    ("24 GHz", "24 GHz"),
                    ("60 GHz", "60 GHz"),
                    ("70-80 GHz", "70-80 GHz"),
                    ("VPN", "VPN"),
                    ("Fiber", "Fiber"),
                    ("Ethernet", "Ethernet"),
                ],
                default=None,
                help_text="The technology used for this link 5Ghz, 60Ghz, fiber, etc.",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="link",
            name="type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("5 GHz", "5 GHz"),
                    ("6 GHz", "6 GHz"),
                    ("24 GHz", "24 GHz"),
                    ("60 GHz", "60 GHz"),
                    ("70-80 GHz", "70-80 GHz"),
                    ("VPN", "VPN"),
                    ("Fiber", "Fiber"),
                    ("Ethernet", "Ethernet"),
                ],
                default=None,
                help_text="The technology used for this link 5Ghz, 60Ghz, fiber, etc.",
                null=True,
            ),
        ),
    ]
