# Generated by Django 4.2.5 on 2023-10-13 07:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("meshapi", "0009_alter_building_id_alter_install_id_alter_member_id_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="building",
            name="bin",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
