# Generated by Django 4.2.13 on 2024-07-07 01:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("meshapi", "0009_member_additional_phone_numbers_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="link",
            name="type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("5 GHz", "Five Ghz"),
                    ("24 GHz", "Twentyfour Ghz"),
                    ("60 GHz", "Sixty Ghz"),
                    ("70-80 GHz", "Seventy Eighty Ghz"),
                    ("VPN", "Vpn"),
                    ("Fiber", "Fiber"),
                    ("Ethernet", "Ethernet"),
                ],
                default=None,
                help_text="The technology used for this link 5Ghz, 60Ghz, fiber, etc.",
                null=True,
            ),
        ),
    ]
