# Generated by Django 4.2.5 on 2023-10-13 07:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("meshapi", "0010_alter_building_bin"),
    ]

    operations = [
        migrations.AlterField(
            model_name="building",
            name="bin",
            field=models.IntegerField(default=69),
            preserve_default=False,
        ),
    ]
