# Generated by Django 4.2.9 on 2024-02-16 02:23

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("meshapi", "0010_alter_link_from_building_alter_link_to_building_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="member",
            old_name="secondary_emails",
            new_name="additional_email_addresses",
        ),
        migrations.RenameField(
            model_name="member",
            old_name="email_address",
            new_name="primary_email_address",
        ),
    ]
