# Generated by Django 4.2.21 on 2025-06-10 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("meshapi", "0010_alter_historicallink_type_alter_link_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="historicalmember",
            name="payment_preference",
            field=models.CharField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name="member",
            name="payment_preference",
            field=models.CharField(blank=True, default=None, null=True),
        ),
    ]
