# Generated by Django 4.2.13 on 2024-08-01 22:36

from django.db import migrations

import meshapi.migrations.util.custom_many_to_many


class Migration(migrations.Migration):
    dependencies = [
        ("meshapi", "0011_los"),
    ]

    operations = [
        migrations.AlterField(
            model_name="building",
            name="nodes",
            field=meshapi.migrations.util.custom_many_to_many.CustomColumnNameManyToManyField(
                blank=True,
                db_from_column_name="building_id",
                db_to_column_name="network_number",
                help_text="All nodes located on the same structure (i.e. a discrete man-made place identified by the same BIN) that this Building is located within.",
                related_name="buildings",
                to="meshapi.node",
            ),
        ),
    ]
