# Generated by Django 4.2.10 on 2024-02-25 17:58

from django.db import migrations, models
import django_jsonform.models.fields


class Migration(migrations.Migration):
    dependencies = [
        ("meshapi", "0011_rename_secondary_emails_member_additional_email_addresses_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="building",
            name="panoramas",
            field=django_jsonform.models.fields.ArrayField(
                base_field=models.URLField(), blank=True, default=list, null=True, size=None
            ),
        ),
        migrations.AlterField(
            model_name="member",
            name="additional_email_addresses",
            field=django_jsonform.models.fields.ArrayField(
                base_field=models.EmailField(max_length=254), blank=True, default=list, null=True, size=None
            ),
        ),
        migrations.AlterModelOptions(
            name="install",
            options={
                "permissions": [
                    ("assign_nn", "Can assign an NN to install"),
                    ("update_panoramas", "Can update panoramas"),
                ]
            },
        ),
    ]
