# Generated by Django 4.2.10 on 2024-02-24 16:26

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("meshapi", "0011_rename_secondary_emails_member_additional_email_addresses_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="building",
            name="panoramas",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.URLField(), blank=True, default=list, null=True, size=None
            ),
        ),
    ]
