# Generated by Django 4.2.9 on 2024-08-05 05:10

import django_jsonform.models.fields
from django.db import migrations, models

import meshapi.validation


class Migration(migrations.Migration):
    dependencies = [
        ("meshapi", "0011_los"),
    ]

    operations = [
        migrations.AlterField(
            model_name="member",
            name="additional_phone_numbers",
            field=django_jsonform.models.fields.ArrayField(
                base_field=models.CharField(),
                blank=True,
                default=list,
                help_text="Any additional phone numbers used by this member",
                null=True,
                size=None,
                validators=[meshapi.validation.validate_multi_phone_number_field],
            ),
        ),
        migrations.AlterField(
            model_name="member",
            name="phone_number",
            field=models.CharField(
                blank=True,
                default=None,
                help_text="A primary contact phone number for this member",
                null=True,
                validators=[meshapi.validation.validate_phone_number_field],
            ),
        ),
    ]
