# Generated by Django 4.2.21 on 2025-06-16 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("meshapi", "0011_historicalmember_payment_preference_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="historicalmember",
            name="payment_preference",
            field=models.CharField(
                blank=True, choices=[(None, "None"), ("cash", "Cash"), ("stripe", "Stripe")], default=None, null=True
            ),
        ),
        migrations.AlterField(
            model_name="member",
            name="payment_preference",
            field=models.CharField(
                blank=True, choices=[(None, "None"), ("cash", "Cash"), ("stripe", "Stripe")], default=None, null=True
            ),
        ),
    ]
