# Generated by Django 4.2.5 on 2023-10-13 07:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("meshapi", "0012_alter_building_network_number"),
    ]

    operations = [
        migrations.AlterField(
            model_name="request",
            name="ticket_id",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
