# Generated by Django 4.2.21 on 2025-09-08 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("meshapi", "0012_alter_historicalmember_payment_preference_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="historicalnode",
            name="placement",
            field=models.CharField(
                choices=[
                    ("rooftop", "Rooftop"),
                    ("balcony", "Balcony"),
                    ("window", "Window"),
                    ("indoor", "Indoor"),
                    ("None", "Unknown"),
                ],
                default="None",
                help_text="The placement of the node within the building it is located on",
            ),
        ),
        migrations.AddField(
            model_name="node",
            name="placement",
            field=models.CharField(
                choices=[
                    ("rooftop", "Rooftop"),
                    ("balcony", "Balcony"),
                    ("window", "Window"),
                    ("indoor", "Indoor"),
                    ("None", "Unknown"),
                ],
                default="None",
                help_text="The placement of the node within the building it is located on",
            ),
        ),
    ]
