# Generated by Django 4.2.9 on 2024-08-06 01:31

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("meshapi", "0012_alter_building_nodes"),
        ("meshapi", "0012_alter_member_additional_phone_numbers_and_more"),
    ]

    operations = []
