# Generated by Django 4.2.10 on 2024-03-03 14:51

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("meshapi", "0012_building_panoramas_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="building",
            name="panoramas",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.URLField(), blank=True, default=list, null=True, size=None
            ),
        ),
    ]
