# Generated by Django 4.2.25 on 2025-10-15 01:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("meshapi", "0013_historicalnode_placement_node_placement"),
    ]

    operations = [
        migrations.AddField(
            model_name="historicalmember",
            name="prefered_language",
            field=models.CharField(
                blank=True, choices=[(None, "None"), ("cash", "Cash"), ("stripe", "Stripe")], default=None, null=True
            ),
        ),
        migrations.AddField(
            model_name="member",
            name="prefered_language",
            field=models.CharField(
                blank=True, choices=[(None, "None"), ("cash", "Cash"), ("stripe", "Stripe")], default=None, null=True
            ),
        ),
    ]
