# Generated by Django 4.2.9 on 2024-08-06 02:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("meshapi", "0013_merge_20240805_2131"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="device",
            name="altitude",
        ),
        migrations.RemoveField(
            model_name="device",
            name="ip_address",
        ),
        migrations.RemoveField(
            model_name="device",
            name="latitude",
        ),
        migrations.RemoveField(
            model_name="device",
            name="longitude",
        ),
        migrations.RemoveField(
            model_name="device",
            name="model",
        ),
        migrations.RemoveField(
            model_name="device",
            name="ssid",
        ),
        migrations.RemoveField(
            model_name="device",
            name="type",
        ),
        migrations.AlterField(
            model_name="device",
            name="name",
            field=models.CharField(
                blank=True,
                default=None,
                help_text="The name of this device, usually configured as the hostname in the device firmware, usually in the format nycmesh-xxxx-yyyy-zzzz, where xxxx is the network number for the node this device is located at, yyyy is the type of the device, and zzzz is the network number of the other side of the link this device creates (if applicable)",
                null=True,
            ),
        ),
    ]
