# Generated by Django 4.2.5 on 2023-10-18 05:02

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("meshapi", "0013_alter_request_ticket_id"),
    ]

    operations = [
        migrations.RenameField(
            model_name="member",
            old_name="phone_numer",
            new_name="phone_number",
        ),
    ]
