# Generated by Django 4.2.26 on 2025-11-16 23:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("meshapi", "0014_alter_historicallink_type_alter_link_type"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="building",
            index=models.Index(fields=["bin"], name="meshapi_bui_bin_1bbc3a_idx"),
        ),
        migrations.AddIndex(
            model_name="building",
            index=models.Index(fields=["street_address"], name="meshapi_bui_street__519551_idx"),
        ),
        migrations.AddIndex(
            model_name="building",
            index=models.Index(fields=["zip_code"], name="meshapi_bui_zip_cod_8a5abf_idx"),
        ),
    ]
