# Generated by Django 4.2.30 on 2026-09-02 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("meshapi", "0014_alter_historicallink_type_alter_link_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="historicalmember",
            name="contact_preference",
            field=models.CharField(
                blank=True,
                choices=[(None, "None"), ("email", "Email"), ("phone", "Phone")],
                default=None,
                help_text="The member's preferred contact method, likely indicated when they submitted the join form",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="member",
            name="contact_preference",
            field=models.CharField(
                blank=True,
                choices=[(None, "None"), ("email", "Email"), ("phone", "Phone")],
                default=None,
                help_text="The member's preferred contact method, likely indicated when they submitted the join form",
                null=True,
            ),
        ),
    ]
