# Generated by Django 4.2.25 on 2025-10-26 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("meshapi", "0014_alter_historicallink_type_alter_link_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="historicallink",
            name="type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("5 GHz", "5 GHz Unspecified"),
                    ("5 GHz Airmax", "5 GHz Airmax"),
                    ("5 GHz WDS", "5 GHz WDS"),
                    ("5 GHz Wlan4", "5 GHz Wlan4"),
                    ("6 GHz", "6 GHz"),
                    ("24 GHz", "24 GHz"),
                    ("60 GHz", "60 GHz"),
                    ("70-80 GHz", "70-80 GHz"),
                    ("VPN", "VPN"),
                    ("Fiber", "Fiber"),
                    ("Ethernet", "Ethernet"),
                ],
                default=None,
                help_text="The technology used for this link 5Ghz, 60Ghz, fiber, etc.",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="link",
            name="type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("5 GHz", "5 GHz Unspecified"),
                    ("5 GHz Airmax", "5 GHz Airmax"),
                    ("5 GHz WDS", "5 GHz WDS"),
                    ("5 GHz Wlan4", "5 GHz Wlan4"),
                    ("6 GHz", "6 GHz"),
                    ("24 GHz", "24 GHz"),
                    ("60 GHz", "60 GHz"),
                    ("70-80 GHz", "70-80 GHz"),
                    ("VPN", "VPN"),
                    ("Fiber", "Fiber"),
                    ("Ethernet", "Ethernet"),
                ],
                default=None,
                help_text="The technology used for this link 5Ghz, 60Ghz, fiber, etc.",
                null=True,
            ),
        ),
    ]
