# Generated by Django 4.2.26 on 2025-11-14 04:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("meshapi", "0014_alter_historicallink_type_alter_link_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="building",
            name="street_address",
            field=models.CharField(
                blank=True,
                db_index=True,
                help_text="Line 1 only of the address of this building: i.e. <house num> <street>",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="historicalbuilding",
            name="street_address",
            field=models.CharField(
                blank=True,
                db_index=True,
                help_text="Line 1 only of the address of this building: i.e. <house num> <street>",
                null=True,
            ),
        ),
    ]
