# Generated by Django 4.2.5 on 2023-10-26 01:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("meshapi", "0001_squashed_0014_rename_phone_numer_member_phone_number"),
    ]

    operations = [
        migrations.AlterField(
            model_name="building",
            name="bin",
            field=models.IntegerField(),
        ),
    ]
