# Generated by Django 4.2.25 on 2025-10-15 01:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("meshapi", "0014_historicalmember_prefered_language_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="historicalmember",
            name="prefered_language",
            field=models.CharField(blank=True, choices=[["EN", "English"], ["SP", "Spanish"]], default=None, null=True),
        ),
        migrations.AlterField(
            model_name="member",
            name="prefered_language",
            field=models.CharField(blank=True, choices=[["EN", "English"], ["SP", "Spanish"]], default=None, null=True),
        ),
    ]
