# Generated by Django 4.2.5 on 2023-12-22 01:20

from django.contrib.auth.models import Group
from django.db import migrations

# Make sure that the basic groups are created.
def create_default_groups(apps, schema_editor):
    Group.objects.get_or_create(name="Installer")
    Group.objects.get_or_create(name="Admin")
    Group.objects.get_or_create(name="ReadOnly")

class Migration(migrations.Migration):
    dependencies = [
        ("meshapi", "0001_squashed_0015_alter_building_bin"),
    ]

    operations = [
        migrations.RunPython(create_default_groups),
    ]
