# Generated by Django 4.2.26 on 2025-11-17 00:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("meshapi", "0015_building_meshapi_bui_bin_1bbc3a_idx_and_more"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="node",
            index=models.Index(fields=["name"], name="meshapi_nod_name_ef4e24_idx"),
        ),
    ]
