# Generated by Django 4.2.9 on 2024-09-08 23:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("meshapi", "0016_alter_los_analysis_date"),
    ]

    operations = [
        migrations.RenameField(
            model_name="install",
            old_name="ticket_id",
            new_name="ticket_number",
        ),
        migrations.AlterField(
            model_name="install",
            name="ticket_number",
            field=models.IntegerField(
                blank=True,
                help_text="The ticket number of the OSTicket used to track communications with the member about this install",
                null=True,
            ),
        ),
    ]
