# Generated by Django 4.2.5 on 2023-12-22 04:53

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("meshapi", "0016_create_default_groups"),
    ]

    operations = [
        migrations.AddField(
            model_name="building",
            name="node_name",
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name="building",
            name="secondary_nn",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.IntegerField(blank=True, null=True), null=True, size=None
            ),
        ),
        migrations.AddField(
            model_name="install",
            name="notes",
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name="install",
            name="referral",
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name="install",
            name="request_date",
            field=models.DateField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name="install",
            name="roof_access",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="install",
            name="ticket_id",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="member",
            name="secondary_emails",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.EmailField(max_length=254), null=True, size=None
            ),
        ),
        migrations.AlterField(
            model_name="install",
            name="install_status",
            field=models.IntegerField(
                choices=[(0, "Open"), (1, "Scheduled"), (2, "Blocked"), (3, "Active"), (4, "Inactive"), (5, "Closed")]
            ),
        ),
        migrations.DeleteModel(
            name="Request",
        ),
    ]
