# Generated by Django 4.2.15 on 2024-09-13 00:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("meshapi", "0016_alter_los_analysis_date"),
    ]

    operations = [
        migrations.CreateModel(
            name="Permission",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
            ],
            options={
                "permissions": (("maintenance_mode", "Can toggle maintenance mode"),),
                "managed": False,
                "default_permissions": (),
            },
        ),
    ]
