# Generated by Django 4.2.5 on 2023-12-23 03:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("meshapi", "0017_building_node_name_building_secondary_nn_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="building",
            old_name="network_number",
            new_name="primary_nn",
        ),
        migrations.RemoveField(
            model_name="building",
            name="secondary_nn",
        ),
        migrations.RemoveField(
            model_name="install",
            name="id",
        ),
        migrations.RemoveField(
            model_name="install",
            name="referral",
        ),
        migrations.AddField(
            model_name="install",
            name="network_number",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="install",
            name="install_number",
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
