# Generated by Django 4.2.5 on 2023-12-23 03:37

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("meshapi", "0020_alter_install_install_number"),
    ]

    operations = [
        migrations.AlterField(
            model_name="install",
            name="install_number",
            field=models.AutoField(db_column="install_number", primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name="install",
            name="network_number",
            field=models.IntegerField(
                blank=True,
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(101),
                    django.core.validators.MaxValueValidator(8192),
                ],
            ),
        ),
    ]
