# Generated by Django 4.2.5 on 2023-12-24 21:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("meshapi", "0021_alter_install_install_number_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="building",
            name="abandon_date",
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name="building",
            name="install_date",
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name="install",
            name="abandon_date",
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name="install",
            name="install_date",
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name="install",
            name="request_date",
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
    ]
