# Generated by Django 4.2.13 on 2024-09-03 04:21

import uuid

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("meshapi", "0023_make_install_number_identity_column"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="building",
            options={"ordering": ["id"]},
        ),
        migrations.AlterModelOptions(
            name="device",
            options={"ordering": [models.OrderBy(models.F("install_date"), descending=True, nulls_last=True)]},
        ),
        migrations.AlterModelOptions(
            name="install",
            options={
                "ordering": ["-install_number"],
                "permissions": [
                    ("assign_nn", "Can assign an NN to install"),
                    ("update_panoramas", "Can update panoramas"),
                ],
            },
        ),
        migrations.AlterModelOptions(
            name="link",
            options={"ordering": ["id"]},
        ),
        migrations.AlterModelOptions(
            name="los",
            options={"ordering": ["id"], "verbose_name": "LOS", "verbose_name_plural": "LOSes"},
        ),
        migrations.AlterModelOptions(
            name="member",
            options={"ordering": ["id"]},
        ),
        migrations.AlterModelOptions(
            name="node",
            options={"ordering": ["network_number"]},
        ),
        migrations.AlterField(
            model_name="install",
            name="install_number",
            field=models.IntegerField(editable=False, unique=True),
        ),
        migrations.AlterField(
            model_name="node",
            name="id",
            field=models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name="node",
            name="network_number",
            field=models.IntegerField(
                blank=True, null=True, unique=True, validators=[django.core.validators.MaxValueValidator(8192)]
            ),
        ),
        migrations.AlterField(
            model_name="member",
            name="primary_email_address",
            field=models.EmailField(
                blank=True, help_text="Primary email address used to contact the member", max_length=254, null=True
            ),
        ),
    ]
