# Generated by Django 4.2.9 on 2024-09-07 18:22

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("meshapi", "0025_rebuild_building_node_m2m_to_fix_dupes"),
    ]

    operations = [
        migrations.AlterField(
            model_name="building",
            name="address_truth_sources",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(
                    choices=[
                        ("OSMNominatim", "OSMNominatim"),
                        ("OSMNominatimZIPOnly", "OSMNominatimZIPOnly"),
                        ("NYCPlanningLabs", "NYCPlanningLabs"),
                        ("PeliasStringParsing", "PeliasStringParsing"),
                        ("ReverseGeocodeFromCoordinates", "ReverseGeocodeFromCoordinates"),
                        ("HumanEntry", "HumanEntry"),
                    ]
                ),
                help_text="A list of strings that answers the question: How was the content of the street address, city, state, and ZIP fields determined? This is useful in understanding the level of validation applied to spreadsheet imported data. Possible values are: OSMNominatim, OSMNominatimZIPOnly, NYCPlanningLabs, PeliasStringParsing, ReverseGeocodeFromCoordinates, HumanEntry. Check the import script for details",
                size=None,
            ),
        ),
    ]
