# Generated by Django 4.2.9 on 2024-09-13 02:20

from django.db import migrations

import meshapi.models.util.auto_incrementing_integer_field


class Migration(migrations.Migration):
    dependencies = [
        ("meshapi", "0025_rebuild_building_node_m2m_to_fix_dupes"),
    ]

    operations = [
        migrations.AlterField(
            model_name="install",
            name="install_number",
            field=meshapi.models.util.auto_incrementing_integer_field.AutoIncrementingIntegerField(
                editable=False, unique=True
            ),
        ),
    ]
