# Generated by Django 4.2.9 on 2024-09-14 18:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("meshapi", "0026_alter_install_install_number"),
    ]

    operations = [
        migrations.AlterField(
            model_name="device",
            name="node",
            field=models.ForeignKey(
                help_text="The logical node this Device is located within. This node's network_number field corresponds to the static IP address and OSPF ID of this device or the DHCP range it receives an address from. The network number is also usually found in the device name",
                on_delete=django.db.models.deletion.PROTECT,
                related_name="devices",
                to="meshapi.node",
            ),
        ),
        migrations.AlterField(
            model_name="install",
            name="node",
            field=models.ForeignKey(
                blank=True,
                help_text="The node this install is associated with. This node's network_number field corresponds to the static IP address and OSPF ID of the router this install utilizes, the DHCP range it receives an address from, etc.",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="installs",
                to="meshapi.node",
            ),
        ),
    ]
