# Generated by Django 4.2.13 on 2024-09-16 23:01

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("meshapi", "0017_permission"),
        ("meshapi", "0027_doc_changes"),
    ]

    operations = []
