# Generated by Django 4.2.13 on 2024-09-16 23:19

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("meshapi", "0017_rename_ticket_number"),
        ("meshapi", "0028_merge_0017_permission_0027_doc_changes"),
    ]

    operations = []
