# Generated by Django 4.2.13 on 2024-09-16 23:38

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("meshapi", "0026_alter_building_address_truth_sources"),
        ("meshapi", "0029_merge_20240916_1919"),
    ]

    operations = []
