# Generated by Django 4.2.15 on 2024-09-19 23:55

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("meshapi", "0031_create_meshdb_ro"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="permission",
            options={
                "default_permissions": (),
                "managed": False,
                "permissions": (
                    ("maintenance_mode", "Can toggle maintenance mode"),
                    ("explorer", "Can access SQL Explorer"),
                ),
            },
        ),
    ]
