# Generated by Django 4.2.13 on 2024-09-23 03:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("meshapi", "0032_alter_permission_options"),
    ]

    operations = [
        migrations.AlterField(
            model_name="building",
            name="nodes",
            field=models.ManyToManyField(
                blank=True,
                help_text="All nodes located on the same structure (i.e. a discrete man-made place identified by the same BIN) that this Building is located within.",
                related_name="buildings",
                to="meshapi.node",
            ),
        ),
    ]
