# Generated by Django 4.2.13 on 2024-09-23 02:55

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("meshapi", "0031_alter_install_ticket_number"),
        ("meshapi", "0032_alter_permission_options"),
    ]

    operations = []
