# Generated by Django 4.2.13 on 2024-09-23 23:06

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("meshapi", "0033_add_simple_history"),
        ("meshapi", "0033_merge_20240922_2255"),
    ]

    operations = []
