# Generated by Django 4.2.9 on 2024-09-24 01:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("meshapi", "0034_merge_20240923_1906"),
    ]

    operations = [
        migrations.AlterField(
            model_name="historicalinstall",
            name="ticket_number",
            field=models.CharField(
                blank=True,
                help_text="The ticket number of the OSTicket used to track communications with the member about this install. Note that although this appears to be an integer, it is not. Leading zeros are important, so this should be stored as a string at all times",
                null=True,
            ),
        ),
    ]
