# Generated by Django 4.2.13 on 2024-10-06 15:25

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("meshapi", "0033_alter_building_nodes"),
        ("meshapi", "0035_alter_historicalinstall_ticket_number"),
    ]

    operations = []
