# Generated by Django 4.2.15 on 2024-11-03 00:14

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("meshapi", "0036_merge_20241006_1125"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Permission",
        ),
    ]
