# Generated by Django 4.2.5 on 2023-09-10 18:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("meshapi", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="building",
            name="panorama_image",
        ),
        migrations.AddField(
            model_name="install",
            name="abandon_date",
            field=models.DateField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name="install",
            name="install_date",
            field=models.DateField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name="install",
            name="building_id",
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to="meshapi.building"),
        ),
        migrations.AlterField(
            model_name="install",
            name="member_id",
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to="meshapi.member"),
        ),
        migrations.AlterField(
            model_name="request",
            name="building_id",
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to="meshapi.building"),
        ),
        migrations.AlterField(
            model_name="request",
            name="install_id",
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to="meshapi.install"),
        ),
        migrations.AlterField(
            model_name="request",
            name="member_id",
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to="meshapi.member"),
        ),
    ]
