# Generated by Django 4.2.5 on 2023-09-10 18:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("meshapi", "0002_remove_building_panorama_image_install_abandon_date_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="request",
            name="install_id",
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, to="meshapi.install"),
        ),
    ]
